# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
name: dotunderscore
title:            dotunderscore
tagline:          by Brian Hough
description: Musings by Brian Hough.
url:              http://dotunderscore.net
paginate:         5
baseurl:          /
author:
  name:           Brian Hough
  url:            https://twitter.com/bwhough
  email:          brian@haverzine.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
  
# Open Graph
og_image: twitterlogo.png # Default image for Open Graph tag
og_image_type: image/png
og_image_width: 500
og_image_height: 500
fb_profile_id: cooltrainer.org
fb_admins: 542154016
fb_appid: 337414769782635