# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
name: dotunderscore
title:            dotunderscore
tagline:          by Brian Hough
description: Musings by Brian Hough.
url:              http://dotunderscore.net
paginate:         5
baseurl:          /
author:
  name:           Brian Hough
  url:            https://twitter.com/bwhough
  email:          brian@haverzine.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole