# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
name: dotunderscore
title:            Brian Hough
tagline:          Multimedia Developer for HC Media, writer, founder of Haverzine. Afflicted with technology addiction disorder. Do what you like, like what you do.

description: Musings by Brian Hough.
url:              http://dotunderscore.net
paginate:         5
baseurl:          /
author:
  name:           Brian Hough
  url:            https://twitter.com/bwhough
  email:          brian@haverzine.com

# Custom vars
version:          2.0.0
highlighter:      rouge
github:
  repo:           https://github.com/poole/poole