# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
name: dotunderscore
title:            Brian Hough
tagline:          Big fan of all that tech nonsense, avid walker. 'Do what you like, like what you do.'

description: Musings by Brian Hough.
url:              http://dotunderscore.net
paginate:         5
baseurl:          /
author:
  name:           Brian Hough
  url:            https://twitter.com/bwhough
  email:          bwhough@tuta.io

# Custom vars
version:          2.0.0
highlighter:      rouge
github:
  repo:           https://github.com/poole/poole